"""SQLAlchemy declarative base and shared column conventions."""

from __future__ import annotations

import uuid
from datetime import UTC, datetime
from typing import Any, ClassVar

from sqlalchemy import DateTime, MetaData, String
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Explicit naming so Alembic generates stable, readable constraint names instead of database
# defaults that differ between PostgreSQL and SQLite and make autogenerated migrations noisy.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base for every model."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    type_annotation_map: ClassVar[dict[Any, Any]] = {
        # Always store timezone-aware timestamps. A naive timestamp in a scheduling system is a
        # latent bug: queue waits are computed by subtraction and a mixed-awareness pair throws.
        datetime: DateTime(timezone=True),
    }


def utcnow() -> datetime:
    """Timezone-aware now, used as a column default."""
    return datetime.now(UTC)


def new_id() -> str:
    """A new primary key.

    String UUIDs rather than autoincrement integers: ids appear in URLs and in audit entries, and a
    sequential id leaks how many jobs exist and lets one be guessed from another.
    """
    return uuid.uuid4().hex


class UuidPrimaryKey:
    """Mixin: a string UUID primary key."""

    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=new_id)


class TimestampedCreation:
    """Mixin: a created-at column."""

    created_at: Mapped[datetime] = mapped_column(default=utcnow, index=True)
