"""initial schema

Revision ID: 31a5453f8d1d
Revises:
Created: 2026-09-29 21:29:09.697865

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "31a5453f8d1d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "experiments",
        sa.Column("label", sa.String(length=128), nullable=False),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.Column("workload", sa.String(length=64), nullable=False),
        sa.Column("executors", sa.Integer(), nullable=False),
        sa.Column("repetition", sa.Integer(), nullable=False),
        sa.Column("plugin_version", sa.String(length=64), nullable=True),
        sa.Column("jenkins_version", sa.String(length=64), nullable=True),
        sa.Column("workload_hash", sa.String(length=64), nullable=True),
        sa.Column("configuration", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_experiments")),
    )
    op.create_index(op.f("ix_experiments_created_at"), "experiments", ["created_at"], unique=False)
    op.create_index(op.f("ix_experiments_label"), "experiments", ["label"], unique=False)
    op.create_table(
        "services",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("repo_url", sa.String(length=512), nullable=False),
        sa.Column("default_branch", sa.String(length=128), nullable=False),
        sa.Column("agent_label", sa.String(length=64), nullable=False),
        sa.Column("build_command", sa.String(length=512), nullable=False),
        sa.Column("test_suites", sa.JSON(), nullable=False),
        sa.Column("deploy_commands", sa.JSON(), nullable=False),
        sa.Column("allowed_environments", sa.JSON(), nullable=False),
        sa.Column("extra_stages", sa.JSON(), nullable=False),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_services")),
    )
    op.create_index(op.f("ix_services_created_at"), "services", ["created_at"], unique=False)
    op.create_index(op.f("ix_services_name"), "services", ["name"], unique=True)
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "audit_logs",
        sa.Column("actor_id", sa.String(length=32), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target", sa.String(length=255), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_audit_logs_actor_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(
        "ix_audit_logs_action_created", "audit_logs", ["action", "created_at"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_actor_id"), "audit_logs", ["actor_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False)
    op.create_table(
        "conversations",
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("assistant", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_conversations_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
    )
    op.create_index(
        op.f("ix_conversations_created_at"), "conversations", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_conversations_user_id"), "conversations", ["user_id"], unique=False)
    op.create_table(
        "experiment_metrics",
        sa.Column("experiment_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("band", sa.String(length=16), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=16), nullable=False),
        sa.Column("std_dev", sa.Float(), nullable=True),
        sa.Column("sample_size", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiments.id"],
            name=op.f("fk_experiment_metrics_experiment_id_experiments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_experiment_metrics")),
        sa.UniqueConstraint("experiment_id", "name", "band", name="experiment_metric"),
    )
    op.create_index(
        op.f("ix_experiment_metrics_experiment_id"),
        "experiment_metrics",
        ["experiment_id"],
        unique=False,
    )
    op.create_table(
        "jobs",
        sa.Column("jenkins_name", sa.String(length=255), nullable=False),
        sa.Column("job_type", sa.String(length=16), nullable=False),
        sa.Column("service_id", sa.String(length=32), nullable=True),
        sa.Column("priority_level", sa.String(length=16), nullable=False),
        sa.Column("depends_on", sa.String(length=1024), nullable=False),
        sa.Column("chain_position", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=32), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_jobs_created_by_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
            name=op.f("fk_jobs_service_id_services"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    op.create_index(op.f("ix_jobs_created_at"), "jobs", ["created_at"], unique=False)
    op.create_index(op.f("ix_jobs_jenkins_name"), "jobs", ["jenkins_name"], unique=True)
    op.create_index(op.f("ix_jobs_service_id"), "jobs", ["service_id"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(
        op.f("ix_notifications_created_at"), "notifications", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False)
    op.create_table(
        "resource_samples",
        sa.Column("experiment_id", sa.String(length=32), nullable=False),
        sa.Column("sampled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("busy_executors", sa.Integer(), nullable=False),
        sa.Column("total_executors", sa.Integer(), nullable=False),
        sa.Column("queue_length", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiments.id"],
            name=op.f("fk_resource_samples_experiment_id_experiments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resource_samples")),
    )
    op.create_index(
        op.f("ix_resource_samples_experiment_id"),
        "resource_samples",
        ["experiment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resource_samples_sampled_at"), "resource_samples", ["sampled_at"], unique=False
    )
    op.create_table(
        "job_runs",
        sa.Column("job_id", sa.String(length=32), nullable=False),
        sa.Column("build_number", sa.Integer(), nullable=False),
        sa.Column("queue_entered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("result", sa.String(length=16), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("queue_wait_ms", sa.Integer(), nullable=True),
        sa.Column("queue_item_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_job_runs_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_runs")),
        sa.UniqueConstraint("job_id", "build_number", name="job_build"),
    )
    op.create_index(op.f("ix_job_runs_created_at"), "job_runs", ["created_at"], unique=False)
    op.create_index(op.f("ix_job_runs_job_id"), "job_runs", ["job_id"], unique=False)
    op.create_index(op.f("ix_job_runs_queue_item_id"), "job_runs", ["queue_item_id"], unique=False)
    op.create_index(
        "ix_job_runs_result_started", "job_runs", ["result", "started_at"], unique=False
    )
    op.create_table(
        "messages",
        sa.Column("conversation_id", sa.String(length=32), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_messages_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
    )
    op.create_index(
        op.f("ix_messages_conversation_id"), "messages", ["conversation_id"], unique=False
    )
    op.create_index(op.f("ix_messages_created_at"), "messages", ["created_at"], unique=False)
    op.create_table(
        "nl_commands",
        sa.Column("message_id", sa.String(length=32), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("parsed_intent", sa.JSON(), nullable=False),
        sa.Column("parser", sa.String(length=16), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("clarification_rounds", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_nl_commands_message_id_messages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nl_commands")),
    )
    op.create_index(op.f("ix_nl_commands_created_at"), "nl_commands", ["created_at"], unique=False)
    op.create_index(op.f("ix_nl_commands_message_id"), "nl_commands", ["message_id"], unique=False)
    op.create_table(
        "generated_pipelines",
        sa.Column("command_id", sa.String(length=32), nullable=False),
        sa.Column("job_type", sa.String(length=16), nullable=False),
        sa.Column("spec_yaml", sa.Text(), nullable=False),
        sa.Column("rendered_artifact", sa.Text(), nullable=False),
        sa.Column("validation_results", sa.JSON(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("approved_by", sa.String(length=32), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("idempotency_key", sa.String(length=64), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.id"],
            name=op.f("fk_generated_pipelines_approved_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["command_id"],
            ["nl_commands.id"],
            name=op.f("fk_generated_pipelines_command_id_nl_commands"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generated_pipelines")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_generated_pipelines_idempotency_key")),
    )
    op.create_index(
        op.f("ix_generated_pipelines_command_id"),
        "generated_pipelines",
        ["command_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_generated_pipelines_created_at"),
        "generated_pipelines",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "llm_calls",
        sa.Column("command_id", sa.String(length=32), nullable=True),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("fallback_used", sa.Boolean(), nullable=False),
        sa.Column("cached", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["command_id"],
            ["nl_commands.id"],
            name=op.f("fk_llm_calls_command_id_nl_commands"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_calls")),
    )
    op.create_index(op.f("ix_llm_calls_command_id"), "llm_calls", ["command_id"], unique=False)
    op.create_index(op.f("ix_llm_calls_created_at"), "llm_calls", ["created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_llm_calls_created_at"), table_name="llm_calls")
    op.drop_index(op.f("ix_llm_calls_command_id"), table_name="llm_calls")
    op.drop_table("llm_calls")
    op.drop_index(op.f("ix_generated_pipelines_created_at"), table_name="generated_pipelines")
    op.drop_index(op.f("ix_generated_pipelines_command_id"), table_name="generated_pipelines")
    op.drop_table("generated_pipelines")
    op.drop_index(op.f("ix_nl_commands_message_id"), table_name="nl_commands")
    op.drop_index(op.f("ix_nl_commands_created_at"), table_name="nl_commands")
    op.drop_table("nl_commands")
    op.drop_index(op.f("ix_messages_created_at"), table_name="messages")
    op.drop_index(op.f("ix_messages_conversation_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index("ix_job_runs_result_started", table_name="job_runs")
    op.drop_index(op.f("ix_job_runs_queue_item_id"), table_name="job_runs")
    op.drop_index(op.f("ix_job_runs_job_id"), table_name="job_runs")
    op.drop_index(op.f("ix_job_runs_created_at"), table_name="job_runs")
    op.drop_table("job_runs")
    op.drop_index(op.f("ix_resource_samples_sampled_at"), table_name="resource_samples")
    op.drop_index(op.f("ix_resource_samples_experiment_id"), table_name="resource_samples")
    op.drop_table("resource_samples")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_created_at"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_jobs_service_id"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_jenkins_name"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_created_at"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_experiment_metrics_experiment_id"), table_name="experiment_metrics")
    op.drop_table("experiment_metrics")
    op.drop_index(op.f("ix_conversations_user_id"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_created_at"), table_name="conversations")
    op.drop_table("conversations")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_id"), table_name="audit_logs")
    op.drop_index("ix_audit_logs_action_created", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_services_name"), table_name="services")
    op.drop_index(op.f("ix_services_created_at"), table_name="services")
    op.drop_table("services")
    op.drop_index(op.f("ix_experiments_label"), table_name="experiments")
    op.drop_index(op.f("ix_experiments_created_at"), table_name="experiments")
    op.drop_table("experiments")
    # ### end Alembic commands ###
